/* eslint-disable react-refresh/only-export-components -- just because */
import "./globals.css";
import "@monorepo/shared/dist/style.css";

import classNames from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Footer } from "./Footer";
import { Header } from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          "flex flex-col items-stretch min-h-screen",
        )}
      >
        <Header />
        <main className="flex flex-auto flex-col items-stretch bg-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
