# Generated by Django 4.2.5 on 2023-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_default_admin_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
